// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: tcwire.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TcWire struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id            string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                             // Unique UUID for this message
	Provider      string   `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`                                 // Descriptive name for the source of the message
	CreatedTs     int64    `protobuf:"varint,3,opt,name=created_ts,json=createdTs,proto3" json:"created_ts,omitempty"`             // Timestamp when the message was created
	Hostname      string   `protobuf:"bytes,4,opt,name=hostname,proto3" json:"hostname,omitempty"`                                 // Hostname of the source or generator of the message
	ProgramName   string   `protobuf:"bytes,5,opt,name=program_name,json=programName,proto3" json:"program_name,omitempty"`        // Program name that generated the message
	ProcessId     int32    `protobuf:"varint,6,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`             // Process Id (PID) that generated the message
	GeneratedBy   string   `protobuf:"bytes,7,opt,name=generated_by,json=generatedBy,proto3" json:"generated_by,omitempty"`        // UserId of the user who generated the message
	MessageType   string   `protobuf:"bytes,8,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`        // Fully qualified message type name
	Payload       []byte   `protobuf:"bytes,9,opt,name=payload,proto3" json:"payload,omitempty"`                                   // Actual message payload converted to byte[]
	ReplyTo       string   `protobuf:"bytes,10,opt,name=reply_to,json=replyTo,proto3" json:"reply_to,omitempty"`                   // Name of the queue where the response will be sent for this message
	CorrelationId string   `protobuf:"bytes,11,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"` // Unique ID to match the response with the request
	Route         []string `protobuf:"bytes,12,rep,name=route,proto3" json:"route,omitempty"`                                      // Array of string, where each string describes the next queue in the chain
	ExpiresInMs   int32    `protobuf:"varint,13,opt,name=expires_in_ms,json=expiresInMs,proto3" json:"expires_in_ms,omitempty"`    // message is set to expire after X milliseconds
}

func (x *TcWire) Reset() {
	*x = TcWire{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tcwire_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TcWire) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TcWire) ProtoMessage() {}

func (x *TcWire) ProtoReflect() protoreflect.Message {
	mi := &file_tcwire_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TcWire.ProtoReflect.Descriptor instead.
func (*TcWire) Descriptor() ([]byte, []int) {
	return file_tcwire_proto_rawDescGZIP(), []int{0}
}

func (x *TcWire) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TcWire) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *TcWire) GetCreatedTs() int64 {
	if x != nil {
		return x.CreatedTs
	}
	return 0
}

func (x *TcWire) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *TcWire) GetProgramName() string {
	if x != nil {
		return x.ProgramName
	}
	return ""
}

func (x *TcWire) GetProcessId() int32 {
	if x != nil {
		return x.ProcessId
	}
	return 0
}

func (x *TcWire) GetGeneratedBy() string {
	if x != nil {
		return x.GeneratedBy
	}
	return ""
}

func (x *TcWire) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *TcWire) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *TcWire) GetReplyTo() string {
	if x != nil {
		return x.ReplyTo
	}
	return ""
}

func (x *TcWire) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *TcWire) GetRoute() []string {
	if x != nil {
		return x.Route
	}
	return nil
}

func (x *TcWire) GetExpiresInMs() int32 {
	if x != nil {
		return x.ExpiresInMs
	}
	return 0
}

var File_tcwire_proto protoreflect.FileDescriptor

var file_tcwire_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x74, 0x63, 0x77, 0x69, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e,
	0x74, 0x75, 0x63, 0x6f, 0x77, 0x73, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x8d,
	0x03, 0x0a, 0x06, 0x54, 0x63, 0x57, 0x69, 0x72, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f,
	0x76, 0x69, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f,
	0x76, 0x69, 0x64, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x5f, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x54, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x21, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x69,
	0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73,
	0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x5f,
	0x62, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61,
	0x74, 0x65, 0x64, 0x42, 0x79, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c,
	0x6f, 0x61, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x5f, 0x74, 0x6f, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x54, 0x6f, 0x12, 0x25, 0x0a,
	0x0e, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18,
	0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x18, 0x0c, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x05, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x12, 0x22, 0x0a, 0x0d, 0x65, 0x78,
	0x70, 0x69, 0x72, 0x65, 0x73, 0x5f, 0x69, 0x6e, 0x5f, 0x6d, 0x73, 0x18, 0x0d, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0b, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x49, 0x6e, 0x4d, 0x73, 0x42, 0x10,
	0x5a, 0x0e, 0x74, 0x75, 0x63, 0x6f, 0x77, 0x73, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tcwire_proto_rawDescOnce sync.Once
	file_tcwire_proto_rawDescData = file_tcwire_proto_rawDesc
)

func file_tcwire_proto_rawDescGZIP() []byte {
	file_tcwire_proto_rawDescOnce.Do(func() {
		file_tcwire_proto_rawDescData = protoimpl.X.CompressGZIP(file_tcwire_proto_rawDescData)
	})
	return file_tcwire_proto_rawDescData
}

var file_tcwire_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_tcwire_proto_goTypes = []interface{}{
	(*TcWire)(nil), // 0: tucows.message.TcWire
}
var file_tcwire_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tcwire_proto_init() }
func file_tcwire_proto_init() {
	if File_tcwire_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tcwire_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TcWire); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tcwire_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tcwire_proto_goTypes,
		DependencyIndexes: file_tcwire_proto_depIdxs,
		MessageInfos:      file_tcwire_proto_msgTypes,
	}.Build()
	File_tcwire_proto = out.File
	file_tcwire_proto_rawDesc = nil
	file_tcwire_proto_goTypes = nil
	file_tcwire_proto_depIdxs = nil
}
